FROM ruby:2.6.5-slim-buster as ruby-dev
RUN apt-get update -y && apt-get install -y build-essential libsqlite3-dev

ADD neato_api /app
WORKDIR /app
RUN gem install bundler --pre && bundle install

FROM gcr.io/distroless/base-debian10:debug

COPY --from=ruby-dev /app /app

COPY --from=ruby-dev /lib/x86_64-linux-gnu/libz.so.* /lib/x86_64-linux-gnu/
COPY --from=ruby-dev /usr/lib/x86_64-linux-gnu/libyaml* /usr/lib/x86_64-linux-gnu/
COPY --from=ruby-dev /usr/lib/x86_64-linux-gnu/libgmp* /usr/lib/x86_64-linux-gnu/
COPY --from=ruby-dev /usr/local/lib/ /usr/local/lib
COPY --from=ruby-dev /usr/local/bin/ /usr/local/bin
COPY --from=ruby-dev /usr/local/bundle /usr/local/bundle

COPY --from=ruby-dev /usr/local/bundle/ruby /usr/local/bundle/ruby
COPY --from=ruby-dev /usr/local/bundle/extensions /usr/local/bundle/extensions

COPY --from=ruby-dev /usr/include/sqlite3.h /usr/include/sqlite3.h
COPY --from=ruby-dev /usr/include/sqlite3ext.h /usr/include/sqlite3ext.h
COPY --from=ruby-dev /usr/lib/x86_64-linux-gnu/libsqlite3.a /usr/lib/x86_64-linux-gnu/libsqlite3.a
COPY --from=ruby-dev /usr/lib/x86_64-linux-gnu/libsqlite3.la /usr/lib/x86_64-linux-gnu/libsqlite3.la
COPY --from=ruby-dev /usr/lib/x86_64-linux-gnu/libsqlite3.so /usr/lib/x86_64-linux-gnu/libsqlite3.so
COPY --from=ruby-dev /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
COPY --from=ruby-dev /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6 /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
COPY --from=ruby-dev /usr/lib/x86_64-linux-gnu/pkgconfig/sqlite3.pc /usr/lib/x86_64-linux-gnu/pkgconfig/sqlite3.pc

COPY --from=ruby-dev /usr/lib/x86_64-linux-gnu/libffi.a /usr/lib/x86_64-linux-gnu/libffi.a
COPY --from=ruby-dev /usr/lib/x86_64-linux-gnu/libffi.so /usr/lib/x86_64-linux-gnu/libffi.so
COPY --from=ruby-dev /usr/lib/x86_64-linux-gnu/libffi.so.6 /usr/lib/x86_64-linux-gnu/libffi.so.6
COPY --from=ruby-dev /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4 /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4

ENV TERM=dumb
ENV HOSTNAME=distroless_ruby
ENV RUBY_DOWNLOAD_SHA256=d5d6da717fd48524596f9b78ac5a2eeb9691753da5c06923a6c31190abe01a62
ENV RUBY_VERSION=2.6.5
ENV PWD=/app
ENV BUNDLE_APP_CONFIG=/usr/local/bundle
ENV RUBY_MAJOR=2.6
ENV HOME=/root
ENV BUNDLE_SILENCE_ROOT_WARNING=1
ENV GEM_HOME=/usr/local/bundle
ENV SHLVL=1
ENV BUNDLE_PATH=/usr/local/bundle
ENV PATH=/usr/local/bundle/bin:/usr/local/bundle/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/busybox

WORKDIR /app

CMD ["/usr/local/bin/ruby", "/app/bin/rails", "server", "--binding", "0.0.0.0", "--port", "3000"]